### ISSUE TITLE
Implement more environments

### ISSUE THREAD

**Issue by epignatelli** [epignatelli/navix#10]
Source:  https://minigrid.farama.org/environments/minigrid/

- [x] MiniGrid-BlockedUnlockPickup-v0
- [x] MiniGrid-LavaCrossingS9N1-v0
- [x] MiniGrid-LavaCrossingS9N2-v0
- [x] MiniGrid-LavaCrossingS9N3-v0
- [x] MiniGrid-LavaCrossingS11N5-v0
- [x] MiniGrid-SimpleCrossingS9N1-v0
- [x] MiniGrid-SimpleCrossingS9N2-v0
- [x] MiniGrid-SimpleCrossingS9N3-v0
- [x] MiniGrid-SimpleCrossingS11N5-v0
- [x] MiniGrid-DistShift1-v0
- [x] MiniGrid-DistShift2-v0
- [x] MiniGrid-DoorKey-5x5-v0
- [x] MiniGrid-DoorKey-6x6-v0
- [x] MiniGrid-DoorKey-8x8-v0
- [x] MiniGrid-DoorKey-16x16-v0
- [x] MiniGrid-Dynamic-Obstacles-5x5-v0
- [x] MiniGrid-Dynamic-Obstacles-Random-5x5-v0
- [x] MiniGrid-Dynamic-Obstacles-6x6-v0
- [x] MiniGrid-Dynamic-Obstacles-Random-6x6-v0
- [x] MiniGrid-Dynamic-Obstacles-8x8-v0
- [x] MiniGrid-Dynamic-Obstacles-16x16-v0
- [x] MiniGrid-Empty-5x5-v0
- [x] MiniGrid-Empty-Random-5x5-v0
- [x] MiniGrid-Empty-6x6-v0
- [x] MiniGrid-Empty-Random-6x6-v0
- [x] MiniGrid-Empty-8x8-v0
- [x] MiniGrid-Empty-16x16-v0
- [x] MiniGrid-Fetch-5x5-N2-v0
- [x] MiniGrid-Fetch-6x6-N2-v0
- [x] MiniGrid-Fetch-8x8-N3-v0
- [x] MiniGrid-FourRooms-v0
- [x] MiniGrid-GoToDoor-5x5-v0
- [x] MiniGrid-GoToDoor-6x6-v0
- [x] MiniGrid-GoToDoor-8x8-v0
- [x] MiniGrid-GoToObject-6x6-N2-v0
- [x] MiniGrid-GoToObject-8x8-N2-v0
- [x] MiniGrid-KeyCorridorS3R1-v0
- [x] MiniGrid-KeyCorridorS3R2-v0
- [x] MiniGrid-KeyCorridorS3R3-v0
- [x] MiniGrid-KeyCorridorS4R3-v0
- [x] MiniGrid-KeyCorridorS5R3-v0
- [x] MiniGrid-KeyCorridorS6R3-v0
- [x] MiniGrid-LavaGapS5-v0
- [x] MiniGrid-LavaGapS6-v0
- [x] MiniGrid-LavaGapS7-v0
- [x] MiniGrid-LockedRoom-v0
- [x] MiniGrid-MemoryS17Random-v0
- [x] MiniGrid-MemoryS13Random-v0
- [x] MiniGrid-MemoryS13-v0
- [x] MiniGrid-MemoryS11-v0
- [x] MiniGrid-MemoryS9-v0
- [x] MiniGrid-MemoryS7-v0
- [x] MiniGrid-MultiRoom-N2-S4-v0
- [x] MiniGrid-MultiRoom-N4-S5-v0 (navix implements this as MiniGrid's `-v1` kwargs (4 rooms), registered under the `-v0` navix id - MiniGrid's own `-v0` is a documented legacy bug actually configured for 6 rooms - see #201)
- [x] MiniGrid-MultiRoom-N6-v0
- [x] MiniGrid-ObstructedMaze-1Dl-v0
- [x] MiniGrid-ObstructedMaze-1Dlh-v0
- [x] MiniGrid-ObstructedMaze-1Dlhb-v0
- [x] MiniGrid-ObstructedMaze-2Dl-v0
- [x] MiniGrid-ObstructedMaze-2Dlh-v0
- [x] MiniGrid-ObstructedMaze-2Dlhb-v0 (navix implements this as MiniGrid's `-v1` behaviour, registered under the `-v0` navix id - see #199)
- [x] MiniGrid-ObstructedMaze-1Q-v0 (navix implements this as MiniGrid's `-v1` behaviour, registered under the `-v0` navix id - see #199)
- [x] MiniGrid-ObstructedMaze-2Q-v0 (navix implements this as MiniGrid's `-v1` behaviour, registered under the `-v0` navix id - see #199)
- [x] MiniGrid-ObstructedMaze-Full-v0 (navix implements this as MiniGrid's `-v1` behaviour, registered under the `-v0` navix id - see #199)
- [x] MiniGrid-ObstructedMaze-2Dlhb-v1 (covered by navix's `-v0` id above, not a separate registration - see #199)
- [x] MiniGrid-ObstructedMaze-1Q-v1 (covered by navix's `-v0` id above, not a separate registration - see #199)
- [x] MiniGrid-ObstructedMaze-2Q-v1 (covered by navix's `-v0` id above, not a separate registration - see #199)
- [x] MiniGrid-ObstructedMaze-Full-v1 (covered by navix's `-v0` id above, not a separate registration - see #199)
- [x] MiniGrid-Playground-v0
- [x] MiniGrid-PutNear-6x6-N2-v0
- [x] MiniGrid-PutNear-8x8-N3-v0
- [x] MiniGrid-RedBlueDoors-6x6-v0
- [x] MiniGrid-RedBlueDoors-8x8-v0
- [x] MiniGrid-Unlock-v0
- [x] MiniGrid-UnlockPickup-v0
